### ISSUE TITLE
RSTATIC#1: deploy 'rstatic' host

### ISSUE THREAD

**Issue by joseosuna** [reddepruebas/rstatic#1]
# Details
**Story Points:**  1 point.

# Description
We need a host to deploy our static resources such as logos, images, docs and others. Our host most be located in http://rstatic.reddepruebas.com.

**User:** Search engines.
**I Want:** Static information about the website is enabled.
**In order to:** Search engines can read it.

**Criteria:**
1. Write URI in a browser and verify each static resource is enabled.

**Examples:**
http://rstatic.reddepruebas.com/logo.gif. 
http://rstatic.reddepruebas.com/copyright.xhtml

# Issue Links
**Blocks**
This issue *blocks*: 
[CONTOOL#4: add website HTML meta tags](https://github.com/reddepruebas/tools/issues/4)

This issue is *cloned* by:
[RSTATIC#1: deploy 'rstatic' host](https://github.com/jtogaf/rstatic/issues/1)
[JTOGAF#9: deploy 'www' host](https://github.com/jtogaf/jtogaf/issues/9)
[OSTUDIORX-RSTATIC#1: deploy 'rstatic' host](https://github.com/ostudiorx/rstatic/issues/1)

# Sub-Tasks
1. [x] [RSTATIC#2: Create a Jboss 7.1 engine in OpenShift.](https://github.com/reddepruebas/rstatic/issues/2)
2. [x] [RSTATIC#3: Add an alias in Open Shift.](https://github.com/reddepruebas/rstatic/issues/3)
3. [x] [RSTATIC#4: Add a CNAME in DNS hosting.](https://github.com/reddepruebas/rstatic/issues/4)
4. [x] [RSTATIC#5: Clone Open Shift Project.](https://github.com/reddepruebas/rstatic/issues/5)
5. [x] [RSTATIC#6: Load static resources.](https://github.com/reddepruebas/rstatic/issues/6)
6. [x] [RSTATIC#7: Link code to GitHub.](https://github.com/reddepruebas/rstatic/issues/7)

# Time Tracking
**Date Started:** Apr 30, 2015.
**Time Spent:** *(eg. 3w 4d 12h)* 2h 30m.
